paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        '200':
          description: 'Successful Response'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: 'Fail response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailResponse'

  /api/products/{pid}:
    get:
      summary: Get product by product id
      parameters:
      - name: pid
        in: path
        required: true
        description: ID of product
        schema:
          $type: String
      tags:
        - Products
      responses:
        '200':
          description: 'Successful Response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: 'Fail response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailResponse'

components:
  schemas:
    FailResponse:
      type: object
      properties:
        status:
          type: string
          description: field to indicate reques transaction status
        message:
          type: string
          description: Error message
      example:
        status: Error
        message: Product does not exist
    Product:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the objecto on DB
        title:
          type: string
          description: Title/Name of the product
        description:
          type: string
          description: The description of the product
        code:
          type: string
          description: Code of product article
        price:
          type: number
          description: The price of the product
        stock:
          type: integer
          description: Current stock of this product
        category:
          type: string
          description: Product category
        thumbnails:
          type: string
          description: Array of products images URLs
        deleted:
          type: boolean
          description: Soft delet flag
        createdAt:
          type: string
          description: Date of creation
        deletedAt:
          type: string
          description: Date of soft deletion
      example:
        _id: "63c9d316a89db3eb82e330e8"
        title: "Test product from postman"
        description: "Producto de prueba"
        code: "CR86A51"
        price: 100
        status: true
        stock: 8
        category: "Test-1"
        thumbnails": [
          "./imgs/img-1.jpg",
          "./imgs/img-1-2.jpg"
        ]
        deleted: false
        createdAt: "2023-01-19T23:32:38.743Z"
        updatedAt: "2023-03-18T21:29:54.497Z"

